### ISSUE TITLE
Validation should check ChangeUnits have constructor

### ISSUE THREAD

**Issue by msmerc** [flamingock/mongock#146]
## Description

`ChangeLogRuntimeImpl` assumes that a `@ChangeUnit` has constructors and that the first constructor is the one it should use.

If this is the case then the 

## PRIORITY

Minor

### Mongock
- Mongock version 5.0.35 standalone

## Steps to Reproduce

Here's my ChangeUnit
```java
    @ChangeUnit(id="mongock 5", order = "23")
    static class Mogock5Migration {
        @Execution
        public void migrationMethod() {
            LOGGER.info("Performing a no-up upgrade");
        }
        @RollbackExecution
        public void noRollback(){}
    }
```

Arguably this is a pointless changeUnit! But it's not obviously invalid.

## Behaviour

**Expected behavior:** [What you expect to happen]

I'd expect `AnnotationProcessor.validateChangeUnit()` to give some helpful error about there needing to be a constructor.

**Actual behavior:** [What actually happens]

Arrayindex out of bounds exception

**Comment by msmerc** [comment]
If there are multiple constructors that might also cause weird behaviour. Perhaps the validator should guard against that too?

**Comment by msmerc** [comment]
And since I'm here :p: 

The exception:
`io.mongock.api.exception.MongockException: ChangeUnit[com.....DatabaseChangelog$Mogock5Migration] must have only one RollbackExecution method`

Is a bit misleading since it implies I have several when in fact I've got none. Could the language be improved? Maybe to "must have exactly one..." - or for another line of code it could say "is missing" vs "has more than one"?

**Comment by dieppa** [comment]
Hello @msmerc , as you pointed this priority ir minor, but you are welcome to raise a PR!

**Comment by thekaleidoscope** [comment]
Hello @dieppa , I had a look at the codebase and wanted to confirm a few things,

1. We only want to allow exactly one constructor in the `@ChangeUnit` class
2. The constructor must have at least one parameter satisfies `Class.isAssignableFrom` MongoOperation or MongoRepository
3. The validation could be done in the process of `ChangeLogService.buildChangeLogInstance`specifically in `annotationProcessor.validateChangeUnit`

Can please confirm/comment on the above? And also, can you please let me know if someone is already working on this and the change is still relevant.

P.S. sorry for the edits, just learnt the difference in [Class.isAssignableFrom, .isInstance and instanceof](https://www.baeldung.com/java-isinstance-isassignablefrom#4-summing-up)

**Comment by dieppa** [comment]
Hello @msmerc 

The error you got `Arrayindex out of bounds exception` is probably related to the fact that Mongock takes the first constructor(`type.getConstructors()[0]`). Even for classes for which you don't explicitly provide a constructor, the empty constructor is provided by default, so this shouldn't be a problem. The only way I can think this could happen if Mongock cannot access to the changeUnit's constructor, for example if it's private.

Regarding your questions.

1. Currently Mongock allows multiple constructor, it won't break, but it's not guaranteed which one of them it will take and . We want to add an annotation to tell Mongock which constructor to take, while you can use the other for other purpose like testing
2. As mentioned in point(1) we want to allow multiple constructor, but telling Mongock which one it should take, rather than not allowing multiple constructor.

We are happy to assist you if you want to raise a PR for this(allow multiple constructor, while allowing to indicate to Mongock which to take). This should be relatively easy

1. Create an annotations in package `io.mongock.api.annotations` to communicate Mongock the constructor to take. It could be called '@ChangeUnitConstructor' or something like that
2. In the class `ChangeLogRuntimeImpl`, method `getConstructor`, implement the logic to take the constructor annotated with the previous annotation or the first one(current implementation) otherwise
3. Add some test to validate it

Let us know if you want to proceed with this and I will personally assist you on this 😃

**Comment by thekaleidoscope** [comment]
Hello @dieppa, I know didn't tag me, so not sure If you were talking to me for the changes, If you were, I'd be glad to have a stab at this.

on 
> the empty constructor is provided by default

This is just the no arg constructor created by default for a class right, but even if this exists, there wouldn't be any mongoTemplate injected, so not sure how a mongock migration can exist without it. Anyway, I guess we can leave that to the discretion of dev.

Also, we should add validation to ensure exactly one constructor is annotated with `ChangeUnitConstructor` or something right?

**Comment by msmerc** [comment]
@dieppa Do you think multiple constructors is a realistic use case? It's probably easier to have the validator generate an error if there are multiple or zero (valid) constructors - after all, only one can be invoked in practice. 

Why make this any more complex?

**Comment by dieppa** [comment]
Hello @thekaleidoscope . Yes, sorry, I was talking to you as you seemed happy to contribute. 

> This is just the no arg constructor created by default for a class right

Yes

> if this exists, there wouldn't be any mongoTemplate injected, so not sure how a mongock migration can exist without it

Currently Mongock takes the first constructor. If it has parameters, it injects them based on the type

> Also, we should add validation to ensure exactly one constructor is annotated with ChangeUnitConstructor or something right?

Yes. The developer would appreciate some validation 😀

**Comment by dieppa** [comment]
@msmerc, while in production only make sense one constructor and that should be good, you may want to have more than one for testing purpose. 

I believe that's not really important, but a nice to have. So you can have these scenarios

- No constructor provided
- Only one constructor provided(no annotation)
- More than one constructor provided(only one of them with annotation)
- More than one constructor provided(with no annotation) -> Exception (this is tricky because it would mean a breaking change. My thinking: Not throwing an exception in version 5 and throw it from version 6)

**Comment by thekaleidoscope** [comment]
I'm summarizing the acceptance criteria that I understood:
1. Existing ChangeUnits should run without any exception but with a warning `Mark one public constructor in the @ChangeUnit <ChangeUnitName> with @ChangeUnitConstructor denoting it's dependecies are to be injected, This will be mandatory with Mongock version 6`
2. New ChangeUnit with no constructor (public and private) should also run without exception but with above warning
3. New ChangeUnit with more than one public constructor without `@ChangeUnitConstructor` should also run without exception but with above warning
3. ChangeUnit without any public constructor but with one or more private constructors should end with exception of message `No public constructors exist for dependency injection, Please provide at least one public constructor with @ChangeUnitConstructor`
4. ChangeUnit with at least one public constructor and with exactly one constructor having `@ChangeUnitConstructor` should execute without any exception or warning
5. ChangeUnit with more than one public constructor and with more than one constructor having `@ChangeUnitConstructor` should end with exception `@ChangeUnitConstructor should be marked exactly once in a ChangeUnit`

please let me know if this looks okay @dieppa @msmerc

**Comment by msmerc** [comment]
@thekaleidoscope - I think you're not being strict enough. @dieppa summarasied it neatly:

These are ok:
* Only one constructor provided (with or without annotation)
* More than one constructor provided (only one of them with annotation)

This generates an error:
* No constructor provided
* More than one constructor provided (multiple have annotation)

This generates a warning:
* More than one constructor provided (none are annotated)

By "constructor" here, we specifically mean "a valid constructor that Mongock can inject dependencies into". So private constructors, constructors with uncomprehendable / uninjectable arguments, constructors with no arguments (including default constructors) simply do not count as "constructors" for the above checks. We shouldn't care if these constructors are present on the objects - but we should word the messages carefully to indicate what we are doing, so instead of saying e.g. `class has no constructors`, say something like `could not find a constructor that Mongock can use for dependency injection`.

Disclaimer - I'm only a Mongock user, so this is simply what I'd like to see. @dieppa  is a project member so what he says goes!

**Comment by dieppa** [comment]
@thekaleidoscope , I will take a look this evening 😉 

Thanks @msmerc

**Comment by thekaleidoscope** [comment]
@msmerc, dieppa did say we don't want to break what already works for version 5, Hence all the warning scenario in version 5, would become error in version 6. This includes the `No constructor provided` scenario. Not sure which else scenario you think I'm being too leniant on.

Agree with the change of wordings,
Suggestions:

Warning for scenario 1, 2, 3: `Mark one constructor in the @ChangeUnit <ChangeUnitName> with @ChangeUnitConstructor for mongock to use for dependency injection, This will be mandatory with Mongock version 6`

Exception in scenario 4: `Could not find a constructor that Mongock can use for dependency injection, Mark one constructor in the @ChangeUnit <ChangeUnitName> with @ChangeUnitConstructor`

Exception in scenario 6: `Expected exactly one constructor to be marked with @ChangeUnitConstructor in @ChangeUnit <ChangeUnitName> , but found <number of constructors with annotation @ChangeUnitConstructor>`

**Comment by msmerc** [comment]
`No Constuctor Provided` is already an error case (try it!). Sure it passes validation, but Mongock will fail when it uses the object! The whole point of this bug report is to make this a validation error too ;)

I'm confused about your scenario numbers, but in a nutshell:

**No valid constuctors:**

> Could not find a constructor that Mongock can use for dependency injection, Mark one constructor in the @ChangeUnit <ChangeUnitName> with @ChangeUnitConstructor

I'd go with: `Could not find a constructor that Mongock can use for dependency injection` - no need to mention the annotation here.

The annotation is an advance case. Most people are not going to need it, so I'd avoid mentioning it unless you've already got multiple eligible constructors.

**More than one valid constructor:**

> Mark one constructor in the @ChangeUnit <ChangeUnitName> with @ChangeUnitConstructor for mongock to use for dependency injection, This will be mandatory with Mongock version 6

I'd go with `Mongock found multiple constructors. Remove, or annotate preferred constructor with @ChangeUnitConstructor `.

Special case if there a multiple _annotated_ constructors:  `Mongock found multiple annotated constructors...` (or if you're lazy, just the same message).

**Comment by dieppa** [comment]
Hi @msmerc  and @thekaleidoscope , I am going to summarise it, as it's getting more complex than it should. I am going to describe the expected behaviour for version 5, which won't throw un exception where it isn't thrown now, just, in some cases, will wrap an existing exception to provide more insight about the error.

### Notes 
- `Constructor` means a constructor that we can retrieve via reflection. Explicitly provided by the developer or the default one. This includes private constructor too, as they can be retrieved by reflections(I believe)
-`Valid constructor` means a constructor that we can get via reflection and use it to instantiate an object without the need of any trick. Explicitly provided by the developer or the default one

Said that

## Scenarios
### Totally valid scenarios
- **Only one valid constructor** provided(with or without annotation)
- **More than one valid constructor** provided (only one of them with annotation)

### Valid but warning
- **More than one constructor(none of them with annotation)**: It uses the first one to instantiate the object and prints a warning: 
`Mongock found multiple constructors for changeUnit[CHANGE_UNIT_ID]. It's recommended to annotate the one you want Mongock to use with @ChangeUnitConstructor. FROM VERSION 6 THIS WILL CAUSE AN ERROR `
 
### Not valid: Exception
- **No valid constructor** provided: Error with message
`Mongock cannot find a valid constructor for changeUnit[CHANGE_UNIT_ID]`


- **More than one valid constructor annotated with @ChangeUnitConstructor**: Error with message
`Found multiple constructors for changeUnit[CHANGE_UNIT_ID] without annotation @ChangeUnitConstructor. Annotate the one you want Mongock to use to instantiate your changeUnit`

## Extra notes

The warning/error messages are intended to be as clear as possible. I am happy for you to slightly modify them as long as they remain clear, concise and provide all the information the developer needs to fix the problem.

- Always indicating the changeId when possible
- Trying to provide the easiest way to make the current code working. For more options or advanced configuration, the developer can go to the documentation. What I mean by this? For example, if the user provides multiple constructors, we should assume there is a reason for that, so we should offer to remove them, just to annotate one of them. Otherwise it can be confusing and the developer just want to make the code work nicely. Knowing he can remove the other constructors, if he wants is secondary.
- Making aware of what will potentially happen in future version if they ignore the warnings


I believe this clarify everything 😃 


Thank you very much to both of you, @msmerc  and @thekaleidoscope!!!
