### ISSUE TITLE
Locked timeout causes acquisition of secondary instance

### ISSUE THREAD

**Issue by miroslavvojtus** [flamingock/mongock#182]
**Describe the bug** 

In default configuration is set lock-acquired-for-minutes to 3 minutes.
If an migration (single change set) takes longer than 3 minutes
Then a secondary instance acquires the lock executing the very same migration causing data corruption

**To Reproduce**

Steps and conditions to reproduce the behavior:
 - Conditions:
    - Mongock: 4.3.8, Spring boot: 2.5.3, Hibernate: 5.5.4
    - Infrastructure: Docker
    - Mongock is implemented as auto configured dependency
    - No specific configuration above the default
       - lock-acquired-for-minutes: 3
 - Steps
    - Add a change set which sleeps (Thread.sleep) for 5+ minutes
    - Start 2+ instances of the same app

**Expected behavior**

Variations:
- If migration is not done within timebox specified by timeout properly terminate all instances with error state in order to be able to identify the problem occured.
- Do not introduce any timeout in default configuration and properly document this behavior
- Enable us to choose how the lock timeout should be resolved (failure, reacquisition etc.).

It MUST not happen that in changelog colection there are 2 entries with EXECUTED stated and the same id

**Logs**

Nothing specific.
Logs just reports acquisition of lock by another instance which starts performing migrations what results in double migration execution and eventual data corruption.

**Comment by dieppa** [comment]
Hello @miroslavvojtus ,

first, thank you for submitting the issue. 

### EXPLANATION
Although I understand what you are saying, I think you don't fully understand how the lock mechanism works. I will just explain some points that seem relevant to clarify 😉 :
- From the lock and Mongock's point of view, a migration can take as long as needed. You may come across other issues with the framework used or even infrastructure orchestrator, but Mongock doesn't care about the migration size.
- Lock timeout is fully configurable. Although we are about to release the new documentation, [here](https://www.mongock.io/spring#building-time-driver) you can see the current one.

Having this clarified, the problem you are having is not because the entire migration or a single changeLog takes longer than the lock timeout. The problem seems to be because a single operation takes longer than the timeout. Mongock in version 4 checks on operation. This means that in every operation it checks it has the lock and time enough to perform the operation. However, if the operation takes too long, the lock can be lost during that time and taken by other process.

### SOLUTION
This has been improved in version 5.0.21.RC. However as we are doing some extra tests,  meanwhile I suggest you to upgrade to Mongock 5 by following this [brief guide](https://github.com/mongock/mongock/blob/develop/QUICK_UPGRADE_VERSION_5.md) and I will confirm by this afternoon when the tests  have been completed and you can check it on your migration.

**Comment by dieppa** [comment]
Hello again @miroslavvojtus ,

we can confirm we have tested the version 5.0.21.RC and should works for you. 

Please confirm it when you possibly can 😃

**Comment by miroslavvojtus** [comment]
Hello @dieppa,

thanks for fast response.

Just to ensure we are on the same page:

> This means that in every operation it checks it has the lock and time enough to perform the operation. However, if the operation takes too long, the lock can be lost during that time and taken by other process.

Your last words describe our problem. Question for me is if it is designed behavior and how to overcome it?

You proposed to install version 5 but question is how it has improved?
What should I check once updated?
Should the single operation taking longer than lock fail or others will not capture the lock (somehow)?

In general having the state as you said "the lock can be lost during that time and taken by other process" seems to me like a problem under some circumstances. Just imagine there would be some migration which adds some definition data. If it runs twice (or more if large scale) it can duplicate the data. This could lead to data inconsistency/corruption or eventual functional denial of service after migration.

We decided for now to go with large enough timeout (24h) and rather manually monitor hanging locks and the whole migration procedure. Otherwise we would have to take into account into each migration that it could eventually run twice and introduce some kind of internal locking there.

### Suggestion:

On top of lock timeout you could add additional state of change log "STARTED". If some change already started but reacquisition of lock occurred the secondary should reject/fail to migrate what should propagate until the system fails in total and we (devOps/administrator) should react.

**Comment by dieppa** [comment]
Hello @miroslavvojtus 

> Your last words describe our problem

Exactly. That's what your issue is about.

> SUGGESTION

Think that Mongock tries to run the distributed migration automatically. This means that it will eventually do the migration, even if it requires some synchronization/re-tries.
We really appreciate your suggestion and it will probably work in your scenario, but not in others and it's not the Mongock's approach. 
As said, it would be probably the right solution in some scenario, but from the Mongock's point of view is not enough. It may happen that the JVM holding the lock gets down abruptaly leaving the lock there, blocking other processes. And there is no other option to  fix it than manually. 

In your case devops/administrator involvement seems fine, but it's not acceptable in other cases. 

However, what you suggest is bassically the same than making the lock acquisition very long(24h for example, like you did). Mongock will release it once finished. So although we provided the improvement to fix it,  this long acquisition approach should work for you anyway.

> Should the single operation taking longer than lock fail or others will not capture the lock (somehow)?

The single operation **won't fail** and the entire migration should succeed. The others won't acquire the lock until is released or expired. Depending on your configuration other processes will fail because haven't been able to acquire the lock within the time window or wait, because the window is bigger than the time taken for the migration to accomplish.

Be ware than in automated infrstructures like Kubernetes is ok to leave them fail, the infrastructure will retry indefinitely.


> What should I check once updated?

We have added our tests, but you could add a test as follow:
- A mongock process(A) takes the lock for 3 minutes
- (A) have a changeLog that sleeps for 5(minutes)
- A second Mongock process(B) starts and make sure it will wait for more than 3 minutes
- Doesn't get the lock until (A) relases

I believe that's enough to prove. You can also make (B) to wait less than 3 minutes, which would make(B) to fail, as it cannot acquire the lock within the time window provided.


I hope it makes sense for you :blush:
