### ISSUE TITLE
Support policy for mongo java drivers 4.1, 4.2 or 4.3 ?

### ISSUE THREAD

**Issue by gaelcrova** [flamingock/mongock#187]
Hi,

From https://www.mongock.io/compatibility-versions-table I can see that you are supporting 4.0.5 version of the mongodb java driver.
Is there any official support for 4.1, 4.2 or 4.3 drivers ? (required to support MongoDB 4.4.x) https://docs.mongodb.com/drivers/java/sync/current/compatibility/

Thanks

**Comment by dieppa** [comment]
Hello, 

currently we haven't update the libraries in the driver for version4. But I believe you can safely use at least 4.2.3. We haven't tested with higher versions.  

Version 5, in it snext RC will be build on latest versions, plus we'll probably upgrade them in version 4 too.
 But that will happen next week.
 
 Regards

**Comment by gaelcrova** [comment]
Ok thanks. I'll wait for next week build then !

**Comment by gaelcrova** [comment]
Hi @dieppa ,
Is there a chance to get a release this week or soon ? 
Thanks
Regards
Gael

**Comment by gaelcrova** [comment]
Hi @osantana85 
Do you know if new release will be available soon ?
Thanks

**Comment by dieppa** [comment]
Hello @gaelcrova ,

don't know what happened, but I didn't realize about this message. We have been working hard.

...And we are still working hard to do the oficial version 5 release. However, it's about documentation mostly.

In order to use `mongodb-driver-sync` **version 4.3.x** you need  to upgrade to vMongock version 5, following [this guide](https://github.com/mongock/mongock/blob/develop/QUICK_UPGRADE_VERSION_5.md). It's a pretty easy process and we believe well explained, but let us know if you need any help

Then you obviously need to import your `mongodb-driver-sync` dependency and one important thing:

> Use directly MongoTemplate in your migration classes, instead of Mongo**ck**Template.

Note that we haven't tried `mongodb-driver-sync` version 4.4.x as it's still in beta, but it should be fine 😉 

Thanks @osantana85 


## UPDATE
I just did a quick test with `mongodb-driver-sync` version 4.4.0-beta1 and it works. Just FYI, it should work with any `mongodb-driver-sync` 4.x.x, as there should not be breaking changes 😃
